### ISSUE TITLE
Can't mark photos to keep

### ISSUE THREAD

**Issue by ioslife** [agross/immich-duplicates#10]
Hi there,

Getting the below error when clicking the keep button or pressing K:

`TypeError: (await O.deleteAsset({ids:G})).data.filter is not a function. (In '(await O.deleteAsset({ids:G})).data.filter(le=>le.status!=="SUCCESS")', '(await O.deleteAsset({ids:G})).data.filter' is undefined)`

Any ideas?

**Comment by agross** [comment]
I confirmed that the error occurred for me as well. Researching now.

**Comment by agross** [comment]
This bug is likely caused because https://github.com/immich-app/immich/pull/4015 changed the response of the `DELETE /asset` endpoint to no longer return content.

**Comment by agross** [comment]
Please test the new commit (an updated docker image is being built right now) and let me know if the issue is fixed for you.

**Comment by ioslife** [comment]
Working now. Thanks!

**Comment by ioslife** [comment]
@agross, Delete All is giving a similar error. 

`TypeError: (await O.deleteAsset({ids:[...s.value.keys()]})).data.filter is not a function. (In '(await O.deleteAsset({ids:[...s.value.keys()]})).data.filter(G=>G.status!=="SUCCESS")', '(await O.deleteAsset({ids:[...s.value.keys()]})).data.filter' is undefined)`

**Comment by agross** [comment]
Thank makes sense since it uses the same endpoint, but I did not change the code that invokes it. An updated image is underway.
