### ISSUE TITLE
Decisionmaking for different filetypes

### ISSUE THREAD

**Issue by ckocyigit** [agross/immich-duplicates#17]
I do have a lot of dupes where one video  (much higher file size) is compared to its thumbnail/picture.

I would like the decisionmaking to choose the video in that case. It could be that this is a user preference but is it possible to integrate that maybe as a setting?

 This would be an example:
 
![grafik](https://github.com/agross/immich-duplicates/assets/60385015/ee61f28c-8198-446b-809b-63d9dc9f548a)

Also maybe a "Delete" button under each dupeview could be helpful to make detailed manual decisionmaking and continuing with ignore(i).

**Comment by agross** [comment]
FYI, the current algorithm prefers bigger files. Your videos will likely be preferred just because of that.

**Comment by ckocyigit** [comment]
Unfortunately not the case, the keep best asset button is greyed out and cant be used thats the entire reason for this issue

**Comment by agross** [comment]
I see: https://github.com/agross/immich-duplicates/blob/master/src/components/DuplicateGroup.vue#L117-L120

**Comment by agross** [comment]
For #18 I added a Delete button for each asset in a group. Does that help to some extend?

**Comment by ckocyigit** [comment]
That's actually exactly what I thought of

**Comment by xeonixo** [comment]
Hi! Works!
Just one small thing that would make it a little easier to use would be if the entity would also disappear after pressing "delete".

**Comment by ckocyigit** [comment]
![grafik](https://github.com/agross/immich-duplicates/assets/60385015/25430e39-1470-4617-a04e-0d8f50464dd5)
This is a bit confusing though and the delete button has no feedback at all which is not trusting 😆

**Comment by agross** [comment]
Fixed
