### ISSUE TITLE
Select wich Photo/Video should be kept

### ISSUE THREAD

**Issue by xeonixo** [agross/immich-duplicates#18]
Currently it's only possible to keep the "best" one. That's not always the case. I have some pictures, which are in HEIC and JPG. I like to keep the JPG more than a smaller HEIC, but the algorithm wants to keep the HEIC.

Could it be possible to select which one I want to keep or maybe a delete button next to the download button?

**Comment by agross** [comment]
Please let me know if it works for you.

**Comment by xeonixo** [comment]
Hi! Works!
Just one small thing that would make it a little easier to use would be if the entity would also disappear after pressing "delete".

**Comment by agross** [comment]
> would also disappear after pressing "delete".

Fixed
