### ISSUE TITLE
Favour HEIC over JPG

### ISSUE THREAD

**Issue by monocycler** [agross/immich-duplicates#21]
Fantastic software! I just removed over 4000 duplicates.

But I am still left with some: One cases is that I for some reason have HEIC and JPG format of the same image.
According to this: https://www.howtogeek.com/345314/what-is-the-heif-or-heic-image-format/ HEIC is better than JPEG so can your tool propose deletion of JPG in favour of HEIC ?

Thanks !

**Comment by agross** [comment]
Hm, I thought @sircharlo implemented that feature in #13, specifically [this piece of code](https://github.com/agross/immich-duplicates/blob/master/src/components/DuplicateGroup.vue#L69-L89) first looks at the resolution and then looks for the file extension.

1. Does the JPEG have a larger resolution than the HEIC?
2. Does the HEIC file name end in `.heic`?

**Comment by agross** [comment]
Closing this as no feedback was received.
