### ISSUE TITLE
Error in step 6: `nginx: [emerg] host not found in upstream "immich.example.com"`

### ISSUE THREAD

**Issue by Qhilm** [agross/immich-duplicates#25]
I get the following error when I run step 6 `docker container run --rm --publish 8080:80 ghcr.io/agross/immich-duplicates-browser`:

```
2024/08/30 07:50:08 [emerg] 1#1: host not found in upstream "immich.example.com" in /etc/nginx/conf.d/immich-proxy.conf:2
nginx: [emerg] host not found in upstream "immich.example.com" in /etc/nginx/conf.d/immich-proxy.conf:2
```

I have configured CORS on my DSM7 Synology box under `/usr/syno/share/nginx/Portal.mustache` follwing [this](https://old.reddit.com/r/synology/comments/px5mrt/adding_cors_headers_to_builtin_nginx_reverse_proxy/) great post. I restarted nginx (`synosystemctl restart nginx`) and tested CORS:

```shell
$ curl -v --request OPTIONS 'https://your-host.here' -H 'Origin: http://some.origin.here' -H 'Access-Control-Request-Method: GET'

[...]

< HTTP/2 204 
< server: nginx
< date: Fri, 30 Aug 2024 08:09:01 GMT
< access-control-allow-origin: *
< access-control-allow-methods: GET, PUT, POST, DELETE, OPTIONS
< access-control-allow-headers: X-Api-Key, User-Agent, Content-Type
< access-control-max-age: 1728000
< content-type: text/plain; charset=utf-8
```

I feel like I'm missing something obvious, but since the URL of the Immich host is defined in the next step, I don't understand why resolving `immich.example.com` is attempted at this step...

**Comment by agross** [comment]
Have a look at this section in the Readme:

The additional argument --env IMMICH_URL=https://immich.example.com must be set to the base address of your Immich installation. For example

**Comment by Qhilm** [comment]
aah, the way it's written it sounds as if it's only required if CORS is NOT configured.
